// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"xcimoc-data-server/models"
)

func newComicDelete(db *gorm.DB, opts ...gen.DOOption) comicDelete {
	_comicDelete := comicDelete{}

	_comicDelete.comicDeleteDo.UseDB(db, opts...)
	_comicDelete.comicDeleteDo.UseModel(&models.ComicDelete{})

	tableName := _comicDelete.comicDeleteDo.TableName()
	_comicDelete.ALL = field.NewAsterisk(tableName)
	_comicDelete.ID = field.NewUint(tableName, "id")
	_comicDelete.UserID = field.NewUint(tableName, "user_id")
	_comicDelete.Source = field.NewInt(tableName, "source")
	_comicDelete.Cid = field.NewString(tableName, "cid")
	_comicDelete.DeleteFav = field.NewBool(tableName, "delete_fav")
	_comicDelete.DeleteHis = field.NewBool(tableName, "delete_his")
	_comicDelete.CreatedAt = field.NewTime(tableName, "created_at")

	_comicDelete.fillFieldMap()

	return _comicDelete
}

type comicDelete struct {
	comicDeleteDo

	ALL       field.Asterisk
	ID        field.Uint
	UserID    field.Uint
	Source    field.Int
	Cid       field.String
	DeleteFav field.Bool
	DeleteHis field.Bool
	CreatedAt field.Time

	fieldMap map[string]field.Expr
}

func (c comicDelete) Table(newTableName string) *comicDelete {
	c.comicDeleteDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c comicDelete) As(alias string) *comicDelete {
	c.comicDeleteDo.DO = *(c.comicDeleteDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *comicDelete) updateTableName(table string) *comicDelete {
	c.ALL = field.NewAsterisk(table)
	c.ID = field.NewUint(table, "id")
	c.UserID = field.NewUint(table, "user_id")
	c.Source = field.NewInt(table, "source")
	c.Cid = field.NewString(table, "cid")
	c.DeleteFav = field.NewBool(table, "delete_fav")
	c.DeleteHis = field.NewBool(table, "delete_his")
	c.CreatedAt = field.NewTime(table, "created_at")

	c.fillFieldMap()

	return c
}

func (c *comicDelete) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *comicDelete) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 7)
	c.fieldMap["id"] = c.ID
	c.fieldMap["user_id"] = c.UserID
	c.fieldMap["source"] = c.Source
	c.fieldMap["cid"] = c.Cid
	c.fieldMap["delete_fav"] = c.DeleteFav
	c.fieldMap["delete_his"] = c.DeleteHis
	c.fieldMap["created_at"] = c.CreatedAt
}

func (c comicDelete) clone(db *gorm.DB) comicDelete {
	c.comicDeleteDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c comicDelete) replaceDB(db *gorm.DB) comicDelete {
	c.comicDeleteDo.ReplaceDB(db)
	return c
}

type comicDeleteDo struct{ gen.DO }

func (c comicDeleteDo) Debug() *comicDeleteDo {
	return c.withDO(c.DO.Debug())
}

func (c comicDeleteDo) WithContext(ctx context.Context) *comicDeleteDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c comicDeleteDo) ReadDB() *comicDeleteDo {
	return c.Clauses(dbresolver.Read)
}

func (c comicDeleteDo) WriteDB() *comicDeleteDo {
	return c.Clauses(dbresolver.Write)
}

func (c comicDeleteDo) Session(config *gorm.Session) *comicDeleteDo {
	return c.withDO(c.DO.Session(config))
}

func (c comicDeleteDo) Clauses(conds ...clause.Expression) *comicDeleteDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c comicDeleteDo) Returning(value interface{}, columns ...string) *comicDeleteDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c comicDeleteDo) Not(conds ...gen.Condition) *comicDeleteDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c comicDeleteDo) Or(conds ...gen.Condition) *comicDeleteDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c comicDeleteDo) Select(conds ...field.Expr) *comicDeleteDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c comicDeleteDo) Where(conds ...gen.Condition) *comicDeleteDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c comicDeleteDo) Order(conds ...field.Expr) *comicDeleteDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c comicDeleteDo) Distinct(cols ...field.Expr) *comicDeleteDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c comicDeleteDo) Omit(cols ...field.Expr) *comicDeleteDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c comicDeleteDo) Join(table schema.Tabler, on ...field.Expr) *comicDeleteDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c comicDeleteDo) LeftJoin(table schema.Tabler, on ...field.Expr) *comicDeleteDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c comicDeleteDo) RightJoin(table schema.Tabler, on ...field.Expr) *comicDeleteDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c comicDeleteDo) Group(cols ...field.Expr) *comicDeleteDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c comicDeleteDo) Having(conds ...gen.Condition) *comicDeleteDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c comicDeleteDo) Limit(limit int) *comicDeleteDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c comicDeleteDo) Offset(offset int) *comicDeleteDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c comicDeleteDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *comicDeleteDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c comicDeleteDo) Unscoped() *comicDeleteDo {
	return c.withDO(c.DO.Unscoped())
}

func (c comicDeleteDo) Create(values ...*models.ComicDelete) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c comicDeleteDo) CreateInBatches(values []*models.ComicDelete, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c comicDeleteDo) Save(values ...*models.ComicDelete) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c comicDeleteDo) First() (*models.ComicDelete, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.ComicDelete), nil
	}
}

func (c comicDeleteDo) Take() (*models.ComicDelete, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.ComicDelete), nil
	}
}

func (c comicDeleteDo) Last() (*models.ComicDelete, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.ComicDelete), nil
	}
}

func (c comicDeleteDo) Find() ([]*models.ComicDelete, error) {
	result, err := c.DO.Find()
	return result.([]*models.ComicDelete), err
}

func (c comicDeleteDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.ComicDelete, err error) {
	buf := make([]*models.ComicDelete, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c comicDeleteDo) FindInBatches(result *[]*models.ComicDelete, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c comicDeleteDo) Attrs(attrs ...field.AssignExpr) *comicDeleteDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c comicDeleteDo) Assign(attrs ...field.AssignExpr) *comicDeleteDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c comicDeleteDo) Joins(fields ...field.RelationField) *comicDeleteDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c comicDeleteDo) Preload(fields ...field.RelationField) *comicDeleteDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c comicDeleteDo) FirstOrInit() (*models.ComicDelete, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.ComicDelete), nil
	}
}

func (c comicDeleteDo) FirstOrCreate() (*models.ComicDelete, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.ComicDelete), nil
	}
}

func (c comicDeleteDo) FindByPage(offset int, limit int) (result []*models.ComicDelete, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c comicDeleteDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c comicDeleteDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c comicDeleteDo) Delete(models ...*models.ComicDelete) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *comicDeleteDo) withDO(do gen.Dao) *comicDeleteDo {
	c.DO = *do.(*gen.DO)
	return c
}
