// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"xcimoc-data-server/models"
)

func newComic(db *gorm.DB, opts ...gen.DOOption) comic {
	_comic := comic{}

	_comic.comicDo.UseDB(db, opts...)
	_comic.comicDo.UseModel(&models.Comic{})

	tableName := _comic.comicDo.TableName()
	_comic.ALL = field.NewAsterisk(tableName)
	_comic.ID = field.NewUint(tableName, "id")
	_comic.UserID = field.NewUint(tableName, "user_id")
	_comic.Source = field.NewInt(tableName, "source")
	_comic.Cid = field.NewString(tableName, "cid")
	_comic.Title = field.NewString(tableName, "title")
	_comic.Cover = field.NewString(tableName, "cover")
	_comic.Update_ = field.NewString(tableName, "update")
	_comic.Finish = field.NewBool(tableName, "finish")
	_comic.Favorite = field.NewInt64(tableName, "favorite")
	_comic.History = field.NewInt64(tableName, "history")
	_comic.Last_ = field.NewString(tableName, "last")
	_comic.Page = field.NewInt(tableName, "page")
	_comic.Chapter = field.NewString(tableName, "chapter")
	_comic.ChapterCount = field.NewInt(tableName, "chapter_count")
	_comic.CreatedAt = field.NewTime(tableName, "created_at")
	_comic.UpdatedAt = field.NewTime(tableName, "updated_at")

	_comic.fillFieldMap()

	return _comic
}

type comic struct {
	comicDo

	ALL          field.Asterisk
	ID           field.Uint
	UserID       field.Uint
	Source       field.Int
	Cid          field.String
	Title        field.String
	Cover        field.String
	Update_      field.String
	Finish       field.Bool
	Favorite     field.Int64
	History      field.Int64
	Last_        field.String
	Page         field.Int
	Chapter      field.String
	ChapterCount field.Int
	CreatedAt    field.Time
	UpdatedAt    field.Time

	fieldMap map[string]field.Expr
}

func (c comic) Table(newTableName string) *comic {
	c.comicDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c comic) As(alias string) *comic {
	c.comicDo.DO = *(c.comicDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *comic) updateTableName(table string) *comic {
	c.ALL = field.NewAsterisk(table)
	c.ID = field.NewUint(table, "id")
	c.UserID = field.NewUint(table, "user_id")
	c.Source = field.NewInt(table, "source")
	c.Cid = field.NewString(table, "cid")
	c.Title = field.NewString(table, "title")
	c.Cover = field.NewString(table, "cover")
	c.Update_ = field.NewString(table, "update")
	c.Finish = field.NewBool(table, "finish")
	c.Favorite = field.NewInt64(table, "favorite")
	c.History = field.NewInt64(table, "history")
	c.Last_ = field.NewString(table, "last")
	c.Page = field.NewInt(table, "page")
	c.Chapter = field.NewString(table, "chapter")
	c.ChapterCount = field.NewInt(table, "chapter_count")
	c.CreatedAt = field.NewTime(table, "created_at")
	c.UpdatedAt = field.NewTime(table, "updated_at")

	c.fillFieldMap()

	return c
}

func (c *comic) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *comic) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 16)
	c.fieldMap["id"] = c.ID
	c.fieldMap["user_id"] = c.UserID
	c.fieldMap["source"] = c.Source
	c.fieldMap["cid"] = c.Cid
	c.fieldMap["title"] = c.Title
	c.fieldMap["cover"] = c.Cover
	c.fieldMap["update"] = c.Update_
	c.fieldMap["finish"] = c.Finish
	c.fieldMap["favorite"] = c.Favorite
	c.fieldMap["history"] = c.History
	c.fieldMap["last"] = c.Last_
	c.fieldMap["page"] = c.Page
	c.fieldMap["chapter"] = c.Chapter
	c.fieldMap["chapter_count"] = c.ChapterCount
	c.fieldMap["created_at"] = c.CreatedAt
	c.fieldMap["updated_at"] = c.UpdatedAt
}

func (c comic) clone(db *gorm.DB) comic {
	c.comicDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c comic) replaceDB(db *gorm.DB) comic {
	c.comicDo.ReplaceDB(db)
	return c
}

type comicDo struct{ gen.DO }

func (c comicDo) Debug() *comicDo {
	return c.withDO(c.DO.Debug())
}

func (c comicDo) WithContext(ctx context.Context) *comicDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c comicDo) ReadDB() *comicDo {
	return c.Clauses(dbresolver.Read)
}

func (c comicDo) WriteDB() *comicDo {
	return c.Clauses(dbresolver.Write)
}

func (c comicDo) Session(config *gorm.Session) *comicDo {
	return c.withDO(c.DO.Session(config))
}

func (c comicDo) Clauses(conds ...clause.Expression) *comicDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c comicDo) Returning(value interface{}, columns ...string) *comicDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c comicDo) Not(conds ...gen.Condition) *comicDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c comicDo) Or(conds ...gen.Condition) *comicDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c comicDo) Select(conds ...field.Expr) *comicDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c comicDo) Where(conds ...gen.Condition) *comicDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c comicDo) Order(conds ...field.Expr) *comicDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c comicDo) Distinct(cols ...field.Expr) *comicDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c comicDo) Omit(cols ...field.Expr) *comicDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c comicDo) Join(table schema.Tabler, on ...field.Expr) *comicDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c comicDo) LeftJoin(table schema.Tabler, on ...field.Expr) *comicDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c comicDo) RightJoin(table schema.Tabler, on ...field.Expr) *comicDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c comicDo) Group(cols ...field.Expr) *comicDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c comicDo) Having(conds ...gen.Condition) *comicDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c comicDo) Limit(limit int) *comicDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c comicDo) Offset(offset int) *comicDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c comicDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *comicDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c comicDo) Unscoped() *comicDo {
	return c.withDO(c.DO.Unscoped())
}

func (c comicDo) Create(values ...*models.Comic) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c comicDo) CreateInBatches(values []*models.Comic, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c comicDo) Save(values ...*models.Comic) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c comicDo) First() (*models.Comic, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.Comic), nil
	}
}

func (c comicDo) Take() (*models.Comic, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.Comic), nil
	}
}

func (c comicDo) Last() (*models.Comic, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.Comic), nil
	}
}

func (c comicDo) Find() ([]*models.Comic, error) {
	result, err := c.DO.Find()
	return result.([]*models.Comic), err
}

func (c comicDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Comic, err error) {
	buf := make([]*models.Comic, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c comicDo) FindInBatches(result *[]*models.Comic, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c comicDo) Attrs(attrs ...field.AssignExpr) *comicDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c comicDo) Assign(attrs ...field.AssignExpr) *comicDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c comicDo) Joins(fields ...field.RelationField) *comicDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c comicDo) Preload(fields ...field.RelationField) *comicDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c comicDo) FirstOrInit() (*models.Comic, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.Comic), nil
	}
}

func (c comicDo) FirstOrCreate() (*models.Comic, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.Comic), nil
	}
}

func (c comicDo) FindByPage(offset int, limit int) (result []*models.Comic, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c comicDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c comicDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c comicDo) Delete(models ...*models.Comic) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *comicDo) withDO(do gen.Dao) *comicDo {
	c.DO = *do.(*gen.DO)
	return c
}
