// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q           = new(Query)
	Comic       *comic
	ComicDelete *comicDelete
	Setting     *setting
	SyncEvent   *syncEvent
	Tag         *tag
	TagRef      *tagRef
	User        *user
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	Comic = &Q.Comic
	ComicDelete = &Q.ComicDelete
	Setting = &Q.Setting
	SyncEvent = &Q.SyncEvent
	Tag = &Q.Tag
	TagRef = &Q.TagRef
	User = &Q.User
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:          db,
		Comic:       newComic(db, opts...),
		ComicDelete: newComicDelete(db, opts...),
		Setting:     newSetting(db, opts...),
		SyncEvent:   newSyncEvent(db, opts...),
		Tag:         newTag(db, opts...),
		TagRef:      newTagRef(db, opts...),
		User:        newUser(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Comic       comic
	ComicDelete comicDelete
	Setting     setting
	SyncEvent   syncEvent
	Tag         tag
	TagRef      tagRef
	User        user
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) UnderlyingDB() *gorm.DB { return q.db }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:          db,
		Comic:       q.Comic.clone(db),
		ComicDelete: q.ComicDelete.clone(db),
		Setting:     q.Setting.clone(db),
		SyncEvent:   q.SyncEvent.clone(db),
		Tag:         q.Tag.clone(db),
		TagRef:      q.TagRef.clone(db),
		User:        q.User.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.clone(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.clone(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:          db,
		Comic:       q.Comic.replaceDB(db),
		ComicDelete: q.ComicDelete.replaceDB(db),
		Setting:     q.Setting.replaceDB(db),
		SyncEvent:   q.SyncEvent.replaceDB(db),
		Tag:         q.Tag.replaceDB(db),
		TagRef:      q.TagRef.replaceDB(db),
		User:        q.User.replaceDB(db),
	}
}

type queryCtx struct {
	Comic       *comicDo
	ComicDelete *comicDeleteDo
	Setting     *settingDo
	SyncEvent   *syncEventDo
	Tag         *tagDo
	TagRef      *tagRefDo
	User        *userDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Comic:       q.Comic.WithContext(ctx),
		ComicDelete: q.ComicDelete.WithContext(ctx),
		Setting:     q.Setting.WithContext(ctx),
		SyncEvent:   q.SyncEvent.WithContext(ctx),
		Tag:         q.Tag.WithContext(ctx),
		TagRef:      q.TagRef.WithContext(ctx),
		User:        q.User.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
