// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"xcimoc-data-server/models"
)

func newTagRef(db *gorm.DB, opts ...gen.DOOption) tagRef {
	_tagRef := tagRef{}

	_tagRef.tagRefDo.UseDB(db, opts...)
	_tagRef.tagRefDo.UseModel(&models.TagRef{})

	tableName := _tagRef.tagRefDo.TableName()
	_tagRef.ALL = field.NewAsterisk(tableName)
	_tagRef.ID = field.NewUint(tableName, "id")
	_tagRef.UserID = field.NewUint(tableName, "user_id")
	_tagRef.TagID = field.NewUint(tableName, "tag_id")
	_tagRef.Source = field.NewInt(tableName, "source")
	_tagRef.Cid = field.NewString(tableName, "cid")

	_tagRef.fillFieldMap()

	return _tagRef
}

type tagRef struct {
	tagRefDo

	ALL    field.Asterisk
	ID     field.Uint
	UserID field.Uint
	TagID  field.Uint
	Source field.Int
	Cid    field.String

	fieldMap map[string]field.Expr
}

func (t tagRef) Table(newTableName string) *tagRef {
	t.tagRefDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t tagRef) As(alias string) *tagRef {
	t.tagRefDo.DO = *(t.tagRefDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *tagRef) updateTableName(table string) *tagRef {
	t.ALL = field.NewAsterisk(table)
	t.ID = field.NewUint(table, "id")
	t.UserID = field.NewUint(table, "user_id")
	t.TagID = field.NewUint(table, "tag_id")
	t.Source = field.NewInt(table, "source")
	t.Cid = field.NewString(table, "cid")

	t.fillFieldMap()

	return t
}

func (t *tagRef) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *tagRef) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 5)
	t.fieldMap["id"] = t.ID
	t.fieldMap["user_id"] = t.UserID
	t.fieldMap["tag_id"] = t.TagID
	t.fieldMap["source"] = t.Source
	t.fieldMap["cid"] = t.Cid
}

func (t tagRef) clone(db *gorm.DB) tagRef {
	t.tagRefDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t tagRef) replaceDB(db *gorm.DB) tagRef {
	t.tagRefDo.ReplaceDB(db)
	return t
}

type tagRefDo struct{ gen.DO }

func (t tagRefDo) Debug() *tagRefDo {
	return t.withDO(t.DO.Debug())
}

func (t tagRefDo) WithContext(ctx context.Context) *tagRefDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t tagRefDo) ReadDB() *tagRefDo {
	return t.Clauses(dbresolver.Read)
}

func (t tagRefDo) WriteDB() *tagRefDo {
	return t.Clauses(dbresolver.Write)
}

func (t tagRefDo) Session(config *gorm.Session) *tagRefDo {
	return t.withDO(t.DO.Session(config))
}

func (t tagRefDo) Clauses(conds ...clause.Expression) *tagRefDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t tagRefDo) Returning(value interface{}, columns ...string) *tagRefDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t tagRefDo) Not(conds ...gen.Condition) *tagRefDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t tagRefDo) Or(conds ...gen.Condition) *tagRefDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t tagRefDo) Select(conds ...field.Expr) *tagRefDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t tagRefDo) Where(conds ...gen.Condition) *tagRefDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t tagRefDo) Order(conds ...field.Expr) *tagRefDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t tagRefDo) Distinct(cols ...field.Expr) *tagRefDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t tagRefDo) Omit(cols ...field.Expr) *tagRefDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t tagRefDo) Join(table schema.Tabler, on ...field.Expr) *tagRefDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t tagRefDo) LeftJoin(table schema.Tabler, on ...field.Expr) *tagRefDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t tagRefDo) RightJoin(table schema.Tabler, on ...field.Expr) *tagRefDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t tagRefDo) Group(cols ...field.Expr) *tagRefDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t tagRefDo) Having(conds ...gen.Condition) *tagRefDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t tagRefDo) Limit(limit int) *tagRefDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t tagRefDo) Offset(offset int) *tagRefDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t tagRefDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *tagRefDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t tagRefDo) Unscoped() *tagRefDo {
	return t.withDO(t.DO.Unscoped())
}

func (t tagRefDo) Create(values ...*models.TagRef) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t tagRefDo) CreateInBatches(values []*models.TagRef, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t tagRefDo) Save(values ...*models.TagRef) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t tagRefDo) First() (*models.TagRef, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.TagRef), nil
	}
}

func (t tagRefDo) Take() (*models.TagRef, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.TagRef), nil
	}
}

func (t tagRefDo) Last() (*models.TagRef, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.TagRef), nil
	}
}

func (t tagRefDo) Find() ([]*models.TagRef, error) {
	result, err := t.DO.Find()
	return result.([]*models.TagRef), err
}

func (t tagRefDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.TagRef, err error) {
	buf := make([]*models.TagRef, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t tagRefDo) FindInBatches(result *[]*models.TagRef, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t tagRefDo) Attrs(attrs ...field.AssignExpr) *tagRefDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t tagRefDo) Assign(attrs ...field.AssignExpr) *tagRefDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t tagRefDo) Joins(fields ...field.RelationField) *tagRefDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t tagRefDo) Preload(fields ...field.RelationField) *tagRefDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t tagRefDo) FirstOrInit() (*models.TagRef, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.TagRef), nil
	}
}

func (t tagRefDo) FirstOrCreate() (*models.TagRef, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.TagRef), nil
	}
}

func (t tagRefDo) FindByPage(offset int, limit int) (result []*models.TagRef, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t tagRefDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t tagRefDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t tagRefDo) Delete(models ...*models.TagRef) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *tagRefDo) withDO(do gen.Dao) *tagRefDo {
	t.DO = *do.(*gen.DO)
	return t
}
