name: Sync Github Repos To Gitee

on:
  workflow_dispatch:
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
  workflow_run:
      workflows: ["Android CI (tag)"]
      types:
        - completed
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Get Repository Info
      run: |
        REPO_NAME=$(echo $GITHUB_REPOSITORY | cut -d'/' -f2)
        REPO_OWNER=$(echo $GITHUB_REPOSITORY | cut -d'/' -f1)
        echo "GIT_REPO_NAME=$REPO_NAME" >> $GITHUB_ENV
        echo "GIT_REPO_OWNER=$REPO_OWNER" >> $GITHUB_ENV

    - name: Sync Github Repos To Gitee  # 名字随便起
      uses: Yikun/hub-mirror-action@master # 使用Yikun/hub-mirror-action
      with:
        src: github/${{env.GIT_REPO_OWNER}}  # 源端账户名(github)
        dst: gitee/${{env.GIT_REPO_OWNER}}   # 目的端账户名(gitee)
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}  # SSH密钥对中的私钥
        dst_token: ${{ secrets.GITEE_TOKEN }}  # Gitee账户的私人令牌
        account_type: user  # 账户类型
        clone_style: "https"  # 使用https方式进行clone，也可以使用ssh
        debug: true  # 启用后会显示所有执行命令
        force_update: true  # 启用后，强制同步，即强制覆盖目的端仓库
        static_list: "${{env.GIT_REPO_NAME}}"  # 静态同步列表，在此填写需要同步的仓库名称，可填写多个
        timeout: '600s'  # git超时设置，超时后会自动重试git操作

   